train:
  _target_: torch.utils.data.DataLoader
  batch_size: 2
  num_workers: 1
  pin_memory: True

inference:
  _target_: torch.utils.data.DataLoader
  batch_size: 2
  num_workers: 1
  pin_memory: True
